const EDIT = {
  EDIT_EVENT: 'EDIT_EVENT',
  EDIT_EVENT_SUCCESS: 'EDIT_EVENT_SUCCESS',
  EDIT_EVENT_FAILURE: 'EDIT_EVENT_FAILURE',
}

const FETCH = {
  FETCH_EVENT: 'FETCH_EVENT',
  FETCH_EVENT_SUCCESS: 'FETCH_EVENT_SUCCESS',
  FETCH_EVENT_FAILURE: 'FETCH_EVENT_FAILURE',
}

const DELETE = {
  DELETE_EVENT: 'DELETE_EVENT',
  DELETE_EVENT_SUCCESS: 'DELETE_EVENT_SUCCESS',
  DELETE_EVENT_FAILURE: 'DELETE_EVENT_FAILURE',
}

const CREATE = {
  CREATE_EVENT: 'CREATE_EVENT',
  CREATE_EVENT_SUCCESS: 'CREATE_EVENT_SUCCESS',
  CREATE_EVENT_FAILURE: 'CREATE_EVENT_FAILURE',
}

export { EDIT, FETCH, DELETE, CREATE }